### ISSUE TITLE
Helpers for annotation generation

### ISSUE THREAD

**Issue by schdaude** [SWISS-MODEL/covid-19-Annotations-on-Structures#20]
The idea here is to have Python helpers to programmatically add and format annotations that are required by the SWISS-MODEL upload form.

**Comment by gtauriello** [comment]
Helper implemented in #21 

@all-contributors please add @schdaude for code

**Comment by schdaude** [comment]
prototype available in utils/sm_annotations.py. I leave this issue open for another day if there are comments/suggestions.
