### ISSUE TITLE
Extracting annotations from structures

### ISSUE THREAD

**Issue by Ninjani** [SWISS-MODEL/covid-19-Annotations-on-Structures#8]
By: Barbara Terlouw, Mehmet Akdel, Janani Durairaj

These are the annotation types/sources that we are planning to work on. We'll be writing scripts such that the annotations can be generated for any PDB file so that it works for new ones as well. These annotations are mostly per structure, per residue, except for the first two. Suggestions welcome! 

* functional domains
* phenotypes
* point mutations
* hydrophobicity
* surface accessibility
* residue fluctuations derived from elastic network models (ENMs) 
* perturbation response from ENMs
* mechanical stiffness from ENMs
* hinge sites from ENMs
* RMSD of residues across structures of the same protein with different ligands bound (this approach can easily be applied to compare COVID proteins to SARS or other related proteins instead)

**Comment by gtauriello** [comment]
@all-contributors please add @BarbaraTerlouw for ideas

As I expect this effort to include contributions from several people, please feel free to acknowledge them using the all-contributors bot at described in the [contribution guidelines](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/blob/master/CONTRIBUTING.md)

**Comment by Ninjani** [comment]
Added a notebook https://github.com/BarbaraTerlouw/covid19/blob/master/Ensemble.ipynb to analyze the variability in RMSD between the different versions of the SARS-Cov2 3CL-PRO protein (with different ligands bound), and a SARS-Cov 3CL-PRO protein.

**Comment by akdel** [comment]
Update on [progress](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/pull/29):

- [ ] functional domains
- [ ] phenotypes
- [ ] point mutations
- [ ] ~hydrophobicity~
- [x] surface accessibility
- [x] residue fluctuations derived from elastic network models (ENMs)
- [x] perturbation response from ENMs
- [x] mechanical stiffness from ENMs
- [x] hinge sites from ENMs
- [x] RMSD of residues across structures of the same protein with different ligands bound

~The annotations are not yet converted to the SWISS-model format.~

[Example annotations](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/pull/29) on 3CL-pro (main protease):
* [anm fluctuations](https://beta.swissmodel.expasy.org/repository/covid_annotation_project/pmFYMy)
* [perturbation effectiveness](https://beta.swissmodel.expasy.org/repository/covid_annotation_project/xJgCxr)
* [perturbation sensitivity](https://beta.swissmodel.expasy.org/repository/covid_annotation_project/aYszHB)
* [mechanical stiffness](https://beta.swissmodel.expasy.org/repository/covid_annotation_project/c8rYEX)
* [rmsd per residue compared all SARS-cov2 main protease structures](https://beta.swissmodel.expasy.org/repository/covid_annotation_project/dQ72wu)
* [pca fluctuations compared all SARS-cov2 main protease structures](https://beta.swissmodel.expasy.org/repository/covid_annotation_project/KkzSE7)

To be able to see each of these annotations: 
1. Click on the protein ID (P0DTD1) after opening one of the above links
2. Choose the 3C-like proteinase 
3. Click on annotations from "Covid-19 Annotations" box

**Comment by gtauriello** [comment]
Nice work. Thanks. On our end we are discussing display issues since by default per-residue annotations get a ball-and-stick display which doesn't really work well for your type of data. As a temp. workaround for the NGL 3D viewer: if you select "Cartoon" view after selecting the annotations you can get rid of the sticks.

**Comment by mlgill** [comment]
@all-contributors please add @mlgill for solvent accessibility and interface annotations

**Comment by akdel** [comment]
We were thinking of representing possible conformational movements for each protein by using:
1. Information from multiple existing structures
2. Predictions from elastic network models

Would this be a good idea?

They can be represented either using arrows on the models or by animating the model:
*Spike protein*
![Spike protein](https://github.com/Ninjani/covid-19-Annotations-on-Structures/raw/master/str_derived_annotations/spike.png)

*3CL-protease*
![](https://github.com/Ninjani/covid-19-Annotations-on-Structures/raw/master/str_derived_annotations/protease.gif)

**Comment by mlgill** [comment]
@akdel Do we know the direction of movement from your calculations? I've seen it done by varying the width of the backbone for NMR spin relaxation measurements, etc.

**Comment by mlgill** [comment]
Greetings all, new to the hackathon and group. I introduced myself in the channel if you're looking for more info. 

Per discussion [here](https://virtualbiohac-xt62674.slack.com/archives/C010ZV9N6FM/p1586369510090900?thread_ts=1586368868.090100&cid=C010ZV9N6FM) I'm going to start working on the solvent accessibility calculations. 

WIP pull request is #34  to track my work

**Comment by akdel** [comment]
> @akdel Do we know the direction of movement from your calculations? I've seen it done by varying the width of the backbone for NMR spin relaxation measurements, etc.

The direction is stored per residue for a given time in normal mode data format. Some more context [here](https://onlinelibrary.wiley.com/doi/full/10.1002/pro.711). Did I understand your question correctly?

**Comment by mlgill** [comment]
> > @akdel Do we know the direction of movement from your calculations? I've seen it done by varying the width of the backbone for NMR spin relaxation measurements, etc.
> 
> The direction is stored per residue for a given time in normal mode data format. Some more context [here](https://onlinelibrary.wiley.com/doi/full/10.1002/pro.711). Did I understand your question correctly?

Yes, that's my question. Thanks -- I was trying to understand how specific the directionality was or if it was more indicative of the magnitude of motions. Sounds like the former.

**Comment by mlgill** [comment]
Have pushed a draft of the code to extract surface accessibility values and write a CSV for a given PDB. What else is needed? Feedback welcome.

https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/pull/34

Thanks.

**Comment by Ninjani** [comment]
Very cool! We can pull your code and add a small function to generate a SWISS-MODEL annotation URL that visualizes the accessibility on the structure if you'd like. I guess we can move on to the integrating other issues? [Interface residues](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/issues/25) or [glycosylation sites](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/issues/11) are still open as far as I can see. Do you have any other ideas?

**Comment by mlgill** [comment]
@Ninjani I'm happy to work on adding the SWISS-MODEL annotation URL to my current PR, if you'd like. [This code](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/pull/29/files) looks like a reference for how to do that, unless you have another example in mind?

After that I'll look into the [glycosylation sites](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/issues/11) work.

**Comment by Ninjani** [comment]
Yes, I think you can use [this script](https://github.com/SWISS-MODEL/covid-19-Annotations-on-Structures/blob/master/utils/sm_annotations.py) from the utils folder combined with the `parse_pdbe.py` script from that pull request to make the annotation file. 

Okay, cool!

**Comment by mlgill** [comment]
Currently working on incorporating the solvent accessibility measurements into @Ninjani 's framework. Had several work interruptions today, but will finish debugging and testing tomorrow.

**Comment by Ninjani** [comment]
@mlgill Made some fixes to the `parse_pdbe.py` file (See #38). There were potentially some bugs in the residue mapping before as we were relying on alignment - now it uses mappings derived from PDBe so should be more correct.

**Comment by mlgill** [comment]
@Ninjani Could you verify that the branch I should be pulling code from in your fork is "master" and not "utils"? Thank you!

**Comment by gtauriello** [comment]
@all-contributors please add @akdel for code

**Comment by gtauriello** [comment]
@all-contributors please add @mlgill  for code
